"""
Stacked Autoencoder (SAE) network for GeoSAE.

The SAE consists of multiple autoencoders stacked together to simultaneously
predict multiple potential field values for different stratigraphic surfaces.

Reference:
    Section 2.2.1 of the GeoSAE paper - Stacked Autoencoder Network Construction
    "To model F potential fields, F stacked autoencoders are used, where the
    corresponding F potential field values are generated by each input coordinate point."
"""

import torch
import torch.nn as nn
from typing import List, Optional, Dict
from .autoencoder import AutoEncoder


class StackedAutoEncoder(nn.Module):
    """
    Stacked Autoencoder Network for multi-potential field prediction.

    This network stacks F autoencoders to predict F potential field values
    from a single input coordinate point (x, y, z). Each autoencoder corresponds
    to a different potential field (stratigraphic surface).

    The stacking operation is represented as:
        SAE = AE_F ° AE_{F-1} ° ... ° AE_2 ° AE_1
    where ° represents the stacking operation between models.
    """

    def __init__(
        self,
        num_potential_fields: int,
        input_dim: int = 3,
        encoder_channels: Optional[List[int]] = None,
        encoder_fc_dim: int = 256,
        decoder_channels: Optional[List[int]] = None,
        beta: float = 1.0,
        share_encoder: bool = False,
    ):
        """
        Initialize the Stacked AutoEncoder.

        Args:
            num_potential_fields: Number of potential fields (F) to predict
            input_dim: Input dimension (typically 3 for x, y, z coordinates)
            encoder_channels: List of channel dimensions for encoder conv layers
            encoder_fc_dim: Dimension of the fully connected layer in encoder
            decoder_channels: List of channel dimensions for decoder conv layers
            beta: Parameter for the Softplus activation function
            share_encoder: If True, share encoder weights across all autoencoders
        """
        super().__init__()

        self.num_potential_fields = num_potential_fields
        self.share_encoder = share_encoder

        # Create individual autoencoders for each potential field
        self.autoencoders = nn.ModuleList()

        for i in range(num_potential_fields):
            ae = AutoEncoder(
                input_dim=input_dim,
                encoder_channels=encoder_channels,
                encoder_fc_dim=encoder_fc_dim,
                decoder_channels=decoder_channels,
                beta=beta,
            )
            self.autoencoders.append(ae)

        # Optionally share encoder weights
        if share_encoder and num_potential_fields > 1:
            # Copy encoder weights from first autoencoder to all others
            for i in range(1, num_potential_fields):
                self.autoencoders[i].encoder = self.autoencoders[0].encoder

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """
        Forward pass: predict all potential field values.

        Args:
            x: Input tensor of shape (batch_size, 3) for coordinates (x, y, z)

        Returns:
            Potential field values of shape (batch_size, num_potential_fields)
        """
        outputs = []
        for ae in self.autoencoders:
            phi = ae(x)
            outputs.append(phi)

        # Stack outputs along the last dimension
        return torch.cat(outputs, dim=-1)

    def forward_single(self, x: torch.Tensor, field_idx: int) -> torch.Tensor:
        """
        Forward pass for a single potential field.

        Args:
            x: Input tensor of shape (batch_size, 3) for coordinates (x, y, z)
            field_idx: Index of the potential field to predict

        Returns:
            Potential field value of shape (batch_size, 1)
        """
        if field_idx < 0 or field_idx >= self.num_potential_fields:
            raise ValueError(f"field_idx must be in [0, {self.num_potential_fields - 1}]")
        return self.autoencoders[field_idx](x)

    def get_gradient(self, x: torch.Tensor, field_idx: int) -> torch.Tensor:
        """
        Compute the gradient of a specific potential field.

        Args:
            x: Input tensor of shape (batch_size, 3)
            field_idx: Index of the potential field

        Returns:
            Gradient tensor of shape (batch_size, 3)
        """
        return self.autoencoders[field_idx].get_gradient(x)

    def get_all_gradients(self, x: torch.Tensor) -> torch.Tensor:
        """
        Compute gradients for all potential fields.

        Args:
            x: Input tensor of shape (batch_size, 3)

        Returns:
            Gradient tensor of shape (batch_size, num_potential_fields, 3)
        """
        gradients = []
        for ae in self.autoencoders:
            grad = ae.get_gradient(x)
            gradients.append(grad.unsqueeze(1))
        return torch.cat(gradients, dim=1)

    def get_gradient_norms(self, x: torch.Tensor) -> torch.Tensor:
        """
        Compute gradient norms for all potential fields.

        Used for the Eikonal constraint.

        Args:
            x: Input tensor of shape (batch_size, 3)

        Returns:
            Gradient norms of shape (batch_size, num_potential_fields)
        """
        norms = []
        for ae in self.autoencoders:
            norm = ae.get_gradient_norm(x)
            norms.append(norm)
        return torch.cat(norms, dim=-1)

    def load_pretrained_weights(self, pretrained_ae: AutoEncoder) -> None:
        """
        Load pre-trained weights from a single autoencoder to all autoencoders.

        This is used after the geometric initialization (pre-training) phase.

        Args:
            pretrained_ae: Pre-trained AutoEncoder model
        """
        pretrained_state = pretrained_ae.state_dict()
        for ae in self.autoencoders:
            ae.load_state_dict(pretrained_state)

    def get_autoencoder(self, field_idx: int) -> AutoEncoder:
        """
        Get a specific autoencoder by index.

        Args:
            field_idx: Index of the potential field

        Returns:
            The AutoEncoder for the specified field
        """
        return self.autoencoders[field_idx]
